[build]
  command = "npm run build"
  publish = "build"
  base = "."

[build.environment]
  REACT_APP_API_URL = "https://sahayogi-api.onrender.com/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
