redirectsOrigin = "config"
plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\safal\\sahayogi\\frontend\\build"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"
base = "C:\\Users\\safal\\sahayogi\\frontend"

[build.environment]
REACT_APP_API_URL = "https://sahayogi-api.onrender.com/api"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]